== Teknisk bruk av Los

#@@@@@@ må gjennomgås og oppdateres# 

Los kan lastes ned og brukes lokalt, f.eks. i en "rullegardin-meny" i en applikasjon der Los skal brukes til å klassifisere innhold. 


=== Los uttrykt i SKOS
Los er publisert i RDF/XML som et SKOS-vokabular. SKOS er en W3C-anbefaling utviklet for å representere thesaurier, klassifikasjonssystemer, taksonomier og kontrollerte vokabular. SKOS er del av en rekke standarder for den semantiske webben som bygger på RDF og RDFS. Hovedformålet med SKOS er å tilby en enkel publisering og bruk av vokabular som lenkede data.

Hver term har en stabil og globalt unik http-URI. URIene er bygd opp med følgende struktur: https://psi.norge.no/los/tema/{term}. URIen for termen “arbeid” blir dermed https://psi.norge.no/los/tema/arbeid[https://psi.norge.no/los/tema/arbeid] og denne gir da svar i rdf-format. En html-visning av termen oppnås ved å legge til .html som suffiks. Lenke til html-representasjon av samme term blir dermed https://psi.norge.no/los/tema/arbeid.html[https://psi.norge.no/los/tema/arbeid.html]

Omskrivningsreglene i selve URIene for særnorske tegn og mellomrom er: +
æ -> a +
ø -> o +
å -> a +
(mellomrom) -> - +
Eksempel:  https://psi.norge.no/los/tema/natur-og-miljo[https://psi.norge.no/los/tema/natur-og-miljo]

I Los er både hovedtemaer, undertemaer og emneord  _SKOS concept_. Disse står i relasjoner til hverandre i et hierarki. Nivå 1 og 2 er et rent hierarki, mens nivå 3 kan være relateres til flere termer på nivå 2. I tillegg har noen emneord assosiative relasjoner seg imellom (skos:related).

Eksempel på undertemet “arbeidsliv” uttrykt i SKOS:

[cols="1,2", options="header"]
|===
| Hva som beskrives: | Hvordan dette er uttrykt i SKOS:

|Referanse til rdf-skjemaet for gjeldende vokabular|`<skos:inScheme rdf:resource="https://psi.norge.no/los/ontologi/tema/>`
|Emneordets foretrukne skrivemåte på nynorsk|`<skos:prefLabel xml:lang="nn">Arbeidsliv</skos:prefLabel>`
|Emneordets foretrukne skrivemåte på bokmål|`<skos:prefLabel xml:lang="nb">Arbeidsliv</skos:prefLabel>`
|Emneordets foretrukne skrivemåte på engelsk|`<skos:prefLabel xml:lang="en">Employment</skos:prefLabel>`
|Referanse til relatert begrep med mer avgrenset betydning (altså et emneord):|`<skos:narrower rdf:resource="https://psi.norge.no/los/ord/sykefravar/>`
|Referanse til begrep med bredere betydning (altså undertemaets hovedtema eller emneordets undertema)|`<skos:broader rdf:resource="https://psi.norge.no/los/tema/arbeid/>`
|===


Videre er emneordet “sykefravær” uttrykt slik i SKOS (denne gangen et eksempel i fullstendig RDF):

----
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:skos="http://www.w3.org/2004/02/skos/core#">
  <rdf:Description rdf:about="https://psi.norge.no/los/ord/sykefravar">
    <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
    <skos:inScheme rdf:resource="https://psi.norge.no/los/ontologi/ord"/>
    <skos:prefLabel lang="en">Sick leave</skos:prefLabel>
    <skos:prefLabel lang="nn">Sjukefråver</skos:prefLabel>
    <skos:prefLabel lang="nb">Sykefravær</skos:prefLabel>
    <skos:hiddenLabel lang="nb">Egenmelding</skos:hiddenLabel>
    <skos:hiddenLabel lang="nn">Eigenmelding</skos:hiddenLabel>
    <skos:hiddenLabel lang="nn">Sjukemelding</skos:hiddenLabel>
    <skos:hiddenLabel lang="nn">Sjukmelding</skos:hiddenLabel>
    <skos:hiddenLabel lang="nb">Sykemelding</skos:hiddenLabel>
    <skos:hiddenLabel lang="nb">Sykmelding</skos:hiddenLabel>
    <skos:note lang="nn">Sjukefråver er fråver frå lønna arbeid på grunn av sjukdom.</skos:note>
    <skos:note lang="nb">Sykefravær er fravær fra lønnet arbeid på grunn av sykdom.</skos:note>
    <skos:related rdf:resource="https://psi.norge.no/los/ord/sykepenger"/>
    <skos:broader rdf:resource="https://psi.norge.no/los/tema/arbeidsliv"/>
  </rdf:Description>
</rdf:RDF>
----



