name: build adocs and publish v1 to production

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  adoc_build:
    name: asciidoctor build
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      files: |
        docs/index.html text/html nb
        docs/files/los-dokumentasjon.pdf application/pdf nb files/los-dokumentasjon.pdf
        docs/files/los-dokumentasjon.epub application/epub+zip nb files/los-dokumentasjon.epub
        docs/images/digitaliseringsdirektoratet.png image/png nb images/digitaliseringsdirektoratet.png
        docs/images/los-struktur.png image/png nb images/los-struktur.png
        docs/images/los-struktur3.png image/png nb images/los-struktur3.png
        docs/images/los.png image/png nb images/los.png
      program_html: "asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc"
      program_pdf: "asciidoctor-pdf -D docs -o files/los-dokumentasjon.pdf -a lang=nb docs/main.adoc"
      program_epub: "asciidoctor-epub3 -D docs -o files/los-dokumentasjon.epub -a lang=nb docs/main.adoc"
      ontology-type: "guide"
      ontology: "los-dokumentasjon"
      host: "https://fellesdatakatalog.digdir.no"
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
